const mousePools = {
    'Meadow': {
        'Cheddar Cheese': [
            {mouse: 'White Mouse', AR: 0.1586},
            {mouse: 'Brown Mouse', AR: 0.1481},
            {mouse: 'Grey Mouse', AR: 0.1396},
            {mouse: 'Spotted Mouse', AR: 0.1251},
            {mouse: 'Cowardly Mouse', AR: 0.1239},
            {mouse: 'Field Mouse', AR: 0.1218},
            {mouse: 'Lightning Rod Mouse', AR: 0.0873},
            {mouse: 'Granite Mouse', AR: 0.0211},
            {mouse: 'Bionic Mouse', AR: 0.0209},
            {mouse: 'Steel Mouse', AR: 0.0204},
            {mouse: 'Dwarf Mouse', AR: 0.0142},
            {mouse: 'Diamond Mouse', AR: 0.0096},
            {mouse: 'Gold Mouse', AR: 0.0095},
        ],
        'Marble Cheese': [
            {mouse: 'White Mouse', AR: 0.1487},
            {mouse: 'Brown Mouse', AR: 0.1239},
            {mouse: 'Grey Mouse', AR: 0.1235},
            {mouse: 'Spotted Mouse', AR: 0.1134},
            {mouse: 'Cowardly Mouse', AR: 0.1134},
            {mouse: 'Field Mouse', AR: 0.1087},
            {mouse: 'Lightning Rod Mouse', AR: 0.0925},
            {mouse: 'Granite Mouse', AR: 0.0452},
            {mouse: 'Bionic Mouse', AR: 0.0318},
            {mouse: 'Steel Mouse', AR: 0.0316},
            {mouse: 'Dwarf Mouse', AR: 0.0274},
            {mouse: 'Diamond Mouse', AR: 0.0177},
            {mouse: 'Gold Mouse', AR: 0.0145},
            {mouse: 'Mole', AR: 0.0077}
        ],
        'Swiss Cheese': [
            {mouse: 'Lightning Rod Mouse', AR: 0.1365},
            {mouse: 'Cowardly Mouse', AR: 0.1347},
            {mouse: 'Field Mouse', AR: 0.1018},
            {mouse: 'Spotted Mouse', AR: 0.0999},
            {mouse: 'Brown Mouse', AR: 0.0828},
            {mouse: 'White Mouse', AR: 0.0788},
            {mouse: 'Grey Mouse', AR: 0.0753},
            {mouse: 'Dwarf Mouse', AR: 0.0622},
            {mouse: 'Bionic Mouse', AR: 0.0410},
            {mouse: 'Diamond Mouse', AR: 0.0408},
            {mouse: 'Steel Mouse', AR: 0.0399},
            {mouse: 'Gold Mouse', AR: 0.0395},
            {mouse: 'Granite Mouse', AR: 0.0386},
            {mouse: 'Mole', AR: 0.0283}
        ],
        'Brie Cheese': [
            {mouse: 'Cowardly Mouse', AR: 0.1508},
            {mouse: 'Spotted Mouse', AR: 0.1016},
            {mouse: 'Field Mouse', AR: 0.0983},
            {mouse: 'Lightning Rod Mouse', AR: 0.0816},
            {mouse: 'Dwarf Mouse', AR: 0.0699},
            {mouse: 'Bionic Mouse', AR: 0.0606},
            {mouse: 'Granite Mouse', AR: 0.0591},
            {mouse: 'Steel Mouse', AR: 0.0584},
            {mouse: 'Brown Mouse', AR: 0.0507},
            {mouse: 'White Mouse', AR: 0.0492},
            {mouse: 'Grey Mouse', AR: 0.0488},
            {mouse: 'Diamond Mouse', AR: 0.0403},
            {mouse: 'Mole', AR: 0.0401},
            {mouse: 'Gold Mouse', AR: 0.0396},
            {mouse: 'Tiny Mouse', AR: 0.0311},
            {mouse: 'Flying Mouse', AR: 0.0199},
        ],
        'SuperBrie+': [
            {mouse: 'Tiny Mouse', AR: 0.1306},
            {mouse: 'Flying Mouse', AR: 0.1019},
            {mouse: 'Cowardly Mouse', AR: 0.1013},
            {mouse: 'Lightning Rod Mouse', AR: 0.0985},
            {mouse: 'Spotted Mouse', AR: 0.0790},
            {mouse: 'Field Mouse', AR: 0.0788},
            {mouse: 'Mole Mouse', AR: 0.0513},
            {mouse: 'Granite Mouse', AR: 0.0504},
            {mouse: 'Bionic Mouse', AR: 0.0500},
            {mouse: 'Steel Mouse', AR: 0.0494},
            {mouse: 'Grey Mouse', AR: 0.0421},
            {mouse: 'White Mouse', AR: 0.0391},
            {mouse: 'Brown Mouse', AR: 0.0387},
            {mouse: 'Diamond Mouse', AR: 0.0302},
            {mouse: 'Gold Mouse', AR: 0.0297},
            {mouse: 'Dwarf Mouse', AR: 0.0291},
        ],
    },

    'Town of Gnawnia': {
        'Cheddar Cheese': [
            {mouse: 'White Mouse', AR: 0.2021},
            {mouse: 'Brown Mouse', AR: 0.1844},
            {mouse: 'Grey Mouse', AR: 0.1733},
            {mouse: 'Cowardly Mouse', AR: 0.1573},
            {mouse: 'Dwarf Mouse', AR: 0.1118},
            {mouse: 'Pugilist Mouse', AR: 0.0360},
            {mouse: 'Bionic Mouse', AR: 0.0255},
            {mouse: 'Gold Mouse', AR: 0.0249},
            {mouse: 'Granite Mouse', AR: 0.0199},
            {mouse: 'Diamond Mouse', AR: 0.0188},
            {mouse: 'Steel Mouse', AR: 0.0177},
            {mouse: 'Longtail Mouse', AR: 0.0172},
            {mouse: 'Zombie Mouse', AR: 0.0111},
        ],
        'Marble Cheese': [
            {mouse: 'Cowardly Mouse', AR: 0.2218},
            {mouse: 'Grey Mouse', AR: 0.1507},
            {mouse: 'Brown Mouse', AR: 0.1494},
            {mouse: 'White Mouse', AR: 0.1415},
            {mouse: 'Dwarf Mouse', AR: 0.1231},
            {mouse: 'Pugilist Mouse', AR: 0.0623},
            {mouse: 'Longtail Mouse', AR: 0.0498},
            {mouse: 'Diamond Mouse', AR: 0.0205},
            {mouse: 'Gold Mouse', AR: 0.0205},
            {mouse: 'Granite Mouse', AR: 0.0199},
            {mouse: 'Steel Mouse', AR: 0.0168},
            {mouse: 'Bionic Mouse', AR: 0.0146},
            {mouse: 'Zombie Mouse', AR: 0.0092},
        ],
        'Swiss Cheese': [
            {mouse: 'Dwarf Mouse', AR: 0.1730},
            {mouse: 'Cowardly Mouse', AR: 0.1249},
            {mouse: 'Longtail Mouse', AR: 0.1212},
            {mouse: 'Grey Mouse', AR: 0.1102},
            {mouse: 'White Mouse', AR: 0.1095},
            {mouse: 'Brown Mouse', AR: 0.1054},
            {mouse: 'Pugilist Mouse', AR: 0.0500},
            {mouse: 'Granite Mouse', AR: 0.0394},
            {mouse: 'Gold Mouse', AR: 0.0389},
            {mouse: 'Bionic Mouse', AR: 0.0384},
            {mouse: 'Diamond Mouse', AR: 0.0357},
            {mouse: 'Steel Mouse', AR: 0.0351},
            {mouse: 'Zombie Mouse', AR: 0.0183},
        ],
        'Brie Cheese': [
            {mouse: 'Cowardly Mouse', AR: 0.1265},
            {mouse: 'Dwarf Mouse', AR: 0.1170},
            {mouse: 'Pugilist Mouse', AR: 0.1158},
            {mouse: 'White Mouse', AR: 0.0868},
            {mouse: 'Grey Mouse', AR: 0.0857},
            {mouse: 'Brown Mouse', AR: 0.0853},
            {mouse: 'Flying Mouse', AR: 0.0667},
            {mouse: 'Speedy Mouse', AR: 0.0520},
            {mouse: 'Longtail Mouse', AR: 0.0485},
            {mouse: 'Granite Mouse', AR: 0.0409},
            {mouse: 'Diamond Mouse', AR: 0.0402},
            {mouse: 'Bionic Mouse', AR: 0.0395},
            {mouse: 'Gold Mouse', AR: 0.0384},
            {mouse: 'Steel Mouse', AR: 0.0380},
            {mouse: 'Zombie Mouse', AR: 0.0187},
        ],
        'SuperBrie+': [
            {mouse: 'Flying Mouse', AR: 0.1170},
            {mouse: 'Cowardly Mouse', AR: 0.0982},
            {mouse: 'Speedy Mouse', AR: 0.0976},
            {mouse: 'Master Burglar Mouse', AR: 0.0658},
            {mouse: 'White Mouse', AR: 0.0649},
            {mouse: 'Grey Mouse', AR: 0.0630},
            {mouse: 'Brown Mouse', AR: 0.0625},
            {mouse: 'Pugilist Mouse', AR: 0.0569},
            {mouse: 'Longtail Mouse', AR: 0.0517},
            {mouse: 'Nibbler Mouse', AR: 0.0479},
            {mouse: 'Magic Mouse', AR: 0.0435},
            {mouse: 'Dwarf Mouse', AR: 0.0393},
            {mouse: 'Silvertail Mouse', AR: 0.0381},
            {mouse: 'Bionic Mouse', AR: 0.0360},
            {mouse: 'Steel Mouse', AR: 0.0355},
            {mouse: 'Granite Mouse', AR: 0.0355},
            {mouse: 'Gold Mouse', AR: 0.0206},
            {mouse: 'Diamond Mouse', AR: 0.0175},
            {mouse: 'Zombie Mouse', AR: 0.0085},
        ],
    },

    'Windmill': {
        'Cheddar Cheese': [
            {mouse: 'White Mouse', AR: 0.1586},
            {mouse: 'Brown Mouse', AR: 0.1481},
            {mouse: 'Grey Mouse', AR: 0.1396},
            {mouse: 'Spotted Mouse', AR: 0.1251},
            {mouse: 'Cowardly Mouse', AR: 0.1239},
            {mouse: 'Field Mouse', AR: 0.1218},
            {mouse: 'Lightning Rod Mouse', AR: 0.0873},
            {mouse: 'Granite Mouse', AR: 0.0211},
            {mouse: 'Bionic Mouse', AR: 0.0209},
            {mouse: 'Steel Mouse', AR: 0.0204},
            {mouse: 'Dwarf Mouse', AR: 0.0142},
            {mouse: 'Diamond Mouse', AR: 0.0096},
            {mouse: 'Gold Mouse', AR: 0.0095},
        ],
        'Marble Cheese': [
            {mouse: 'White Mouse', AR: 0.1487},
            {mouse: 'Brown Mouse', AR: 0.1239},
            {mouse: 'Grey Mouse', AR: 0.1235},
            {mouse: 'Spotted Mouse', AR: 0.1134},
            {mouse: 'Cowardly Mouse', AR: 0.1134},
            {mouse: 'Field Mouse', AR: 0.1087},
            {mouse: 'Lightning Rod Mouse', AR: 0.0925},
            {mouse: 'Granite Mouse', AR: 0.0452},
            {mouse: 'Bionic Mouse', AR: 0.0318},
            {mouse: 'Steel Mouse', AR: 0.0316},
            {mouse: 'Dwarf Mouse', AR: 0.0274},
            {mouse: 'Diamond Mouse', AR: 0.0177},
            {mouse: 'Gold Mouse', AR: 0.0145},
            {mouse: 'Mole', AR: 0.0077}
        ],
        'Swiss Cheese': [
            {mouse: 'Lightning Rod Mouse', AR: 0.1365},
            {mouse: 'Cowardly Mouse', AR: 0.1347},
            {mouse: 'Field Mouse', AR: 0.1018},
            {mouse: 'Spotted Mouse', AR: 0.0999},
            {mouse: 'Brown Mouse', AR: 0.0828},
            {mouse: 'White Mouse', AR: 0.0788},
            {mouse: 'Grey Mouse', AR: 0.0753},
            {mouse: 'Dwarf Mouse', AR: 0.0622},
            {mouse: 'Bionic Mouse', AR: 0.0410},
            {mouse: 'Diamond Mouse', AR: 0.0408},
            {mouse: 'Steel Mouse', AR: 0.0399},
            {mouse: 'Gold Mouse', AR: 0.0395},
            {mouse: 'Granite Mouse', AR: 0.0386},
            {mouse: 'Mole', AR: 0.0283}
        ],
        'Brie Cheese': [
            {mouse: 'Cowardly Mouse', AR: 0.1508},
            {mouse: 'Spotted Mouse', AR: 0.1016},
            {mouse: 'Field Mouse', AR: 0.0983},
            {mouse: 'Lightning Rod Mouse', AR: 0.0816},
            {mouse: 'Dwarf Mouse', AR: 0.0699},
            {mouse: 'Bionic Mouse', AR: 0.0606},
            {mouse: 'Granite Mouse', AR: 0.0591},
            {mouse: 'Steel Mouse', AR: 0.0584},
            {mouse: 'Brown Mouse', AR: 0.0507},
            {mouse: 'White Mouse', AR: 0.0492},
            {mouse: 'Grey Mouse', AR: 0.0488},
            {mouse: 'Diamond Mouse', AR: 0.0403},
            {mouse: 'Mole', AR: 0.0401},
            {mouse: 'Gold Mouse', AR: 0.0396},
            {mouse: 'Tiny Mouse', AR: 0.0311},
            {mouse: 'Flying Mouse', AR: 0.0199},
        ],
        'SuperBrie+': [
            {mouse: 'Tiny Mouse', AR: 0.1306},
            {mouse: 'Flying Mouse', AR: 0.1019},
            {mouse: 'Cowardly Mouse', AR: 0.1013},
            {mouse: 'Lightning Rod Mouse', AR: 0.0985},
            {mouse: 'Spotted Mouse', AR: 0.0790},
            {mouse: 'Field Mouse', AR: 0.0788},
            {mouse: 'Mole Mouse', AR: 0.0513},
            {mouse: 'Granite Mouse', AR: 0.0504},
            {mouse: 'Bionic Mouse', AR: 0.0500},
            {mouse: 'Steel Mouse', AR: 0.0494},
            {mouse: 'Grey Mouse', AR: 0.0421},
            {mouse: 'White Mouse', AR: 0.0391},
            {mouse: 'Brown Mouse', AR: 0.0387},
            {mouse: 'Diamond Mouse', AR: 0.0302},
            {mouse: 'Gold Mouse', AR: 0.0297},
            {mouse: 'Dwarf Mouse', AR: 0.0291},
        ],
    },

    'Calm Clearing': {
        'Cheddar Cheese': [
            {mouse: 'White Mouse', AR: 0.1586},
            {mouse: 'Brown Mouse', AR: 0.1481},
            {mouse: 'Grey Mouse', AR: 0.1396},
            {mouse: 'Spotted Mouse', AR: 0.1251},
            {mouse: 'Cowardly Mouse', AR: 0.1239},
            {mouse: 'Field Mouse', AR: 0.1218},
            {mouse: 'Lightning Rod Mouse', AR: 0.0873},
            {mouse: 'Granite Mouse', AR: 0.0211},
            {mouse: 'Bionic Mouse', AR: 0.0209},
            {mouse: 'Steel Mouse', AR: 0.0204},
            {mouse: 'Dwarf Mouse', AR: 0.0142},
            {mouse: 'Diamond Mouse', AR: 0.0096},
            {mouse: 'Gold Mouse', AR: 0.0095},
        ],
        'Marble Cheese': [
            {mouse: 'White Mouse', AR: 0.1487},
            {mouse: 'Brown Mouse', AR: 0.1239},
            {mouse: 'Grey Mouse', AR: 0.1235},
            {mouse: 'Spotted Mouse', AR: 0.1134},
            {mouse: 'Cowardly Mouse', AR: 0.1134},
            {mouse: 'Field Mouse', AR: 0.1087},
            {mouse: 'Lightning Rod Mouse', AR: 0.0925},
            {mouse: 'Granite Mouse', AR: 0.0452},
            {mouse: 'Bionic Mouse', AR: 0.0318},
            {mouse: 'Steel Mouse', AR: 0.0316},
            {mouse: 'Dwarf Mouse', AR: 0.0274},
            {mouse: 'Diamond Mouse', AR: 0.0177},
            {mouse: 'Gold Mouse', AR: 0.0145},
            {mouse: 'Mole', AR: 0.0077}
        ],
        'Swiss Cheese': [
            {mouse: 'Lightning Rod Mouse', AR: 0.1365},
            {mouse: 'Cowardly Mouse', AR: 0.1347},
            {mouse: 'Field Mouse', AR: 0.1018},
            {mouse: 'Spotted Mouse', AR: 0.0999},
            {mouse: 'Brown Mouse', AR: 0.0828},
            {mouse: 'White Mouse', AR: 0.0788},
            {mouse: 'Grey Mouse', AR: 0.0753},
            {mouse: 'Dwarf Mouse', AR: 0.0622},
            {mouse: 'Bionic Mouse', AR: 0.0410},
            {mouse: 'Diamond Mouse', AR: 0.0408},
            {mouse: 'Steel Mouse', AR: 0.0399},
            {mouse: 'Gold Mouse', AR: 0.0395},
            {mouse: 'Granite Mouse', AR: 0.0386},
            {mouse: 'Mole', AR: 0.0283}
        ],
        'Brie Cheese': [
            {mouse: 'Cowardly Mouse', AR: 0.1508},
            {mouse: 'Spotted Mouse', AR: 0.1016},
            {mouse: 'Field Mouse', AR: 0.0983},
            {mouse: 'Lightning Rod Mouse', AR: 0.0816},
            {mouse: 'Dwarf Mouse', AR: 0.0699},
            {mouse: 'Bionic Mouse', AR: 0.0606},
            {mouse: 'Granite Mouse', AR: 0.0591},
            {mouse: 'Steel Mouse', AR: 0.0584},
            {mouse: 'Brown Mouse', AR: 0.0507},
            {mouse: 'White Mouse', AR: 0.0492},
            {mouse: 'Grey Mouse', AR: 0.0488},
            {mouse: 'Diamond Mouse', AR: 0.0403},
            {mouse: 'Mole', AR: 0.0401},
            {mouse: 'Gold Mouse', AR: 0.0396},
            {mouse: 'Tiny Mouse', AR: 0.0311},
            {mouse: 'Flying Mouse', AR: 0.0199},
        ],
        'SuperBrie+': [
            {mouse: 'Tiny Mouse', AR: 0.1306},
            {mouse: 'Flying Mouse', AR: 0.1019},
            {mouse: 'Cowardly Mouse', AR: 0.1013},
            {mouse: 'Lightning Rod Mouse', AR: 0.0985},
            {mouse: 'Spotted Mouse', AR: 0.0790},
            {mouse: 'Field Mouse', AR: 0.0788},
            {mouse: 'Mole Mouse', AR: 0.0513},
            {mouse: 'Granite Mouse', AR: 0.0504},
            {mouse: 'Bionic Mouse', AR: 0.0500},
            {mouse: 'Steel Mouse', AR: 0.0494},
            {mouse: 'Grey Mouse', AR: 0.0421},
            {mouse: 'White Mouse', AR: 0.0391},
            {mouse: 'Brown Mouse', AR: 0.0387},
            {mouse: 'Diamond Mouse', AR: 0.0302},
            {mouse: 'Gold Mouse', AR: 0.0297},
            {mouse: 'Dwarf Mouse', AR: 0.0291},
        ],
    }
};

function checkMP() {
    for (const [key, value] of Object.entries(mousePools)) {
        console.log(key);
        for (const [key, innerValue] of Object.entries(value)) {
            let val = 0;
            for (let mouse of innerValue) {
                val += mouse.AR;
            }
            console.log(val);
        }
    }
}

checkMP();